-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity rsa is
generic (
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 8;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32 );
port (
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    interrupt : OUT STD_LOGIC );
end;


architecture behav of rsa is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "rsa_rsa,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=6.882000,HLS_SYN_LAT=295425,HLS_SYN_TPT=295426,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=995608,HLS_SYN_LUT=403935,HLS_VERSION=2022_2}";
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal ap_rst_n_inv : STD_LOGIC;
    signal d : STD_LOGIC_VECTOR (255 downto 0);
    signal N : STD_LOGIC_VECTOR (255 downto 0);
    signal y : STD_LOGIC_VECTOR (255 downto 0);
    signal ap_start : STD_LOGIC;
    signal ap_ready : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal mod_exp_U0_ap_start : STD_LOGIC;
    signal mod_exp_U0_ap_done : STD_LOGIC;
    signal mod_exp_U0_ap_continue : STD_LOGIC;
    signal mod_exp_U0_ap_idle : STD_LOGIC;
    signal mod_exp_U0_ap_ready : STD_LOGIC;
    signal mod_exp_U0_ap_return : STD_LOGIC_VECTOR (255 downto 0);
    signal result_V_full_n : STD_LOGIC;
    signal Block_entry46_proc_U0_ap_start : STD_LOGIC;
    signal Block_entry46_proc_U0_ap_done : STD_LOGIC;
    signal Block_entry46_proc_U0_ap_continue : STD_LOGIC;
    signal Block_entry46_proc_U0_ap_idle : STD_LOGIC;
    signal Block_entry46_proc_U0_ap_ready : STD_LOGIC;
    signal Block_entry46_proc_U0_x : STD_LOGIC_VECTOR (255 downto 0);
    signal Block_entry46_proc_U0_x_ap_vld : STD_LOGIC;
    signal result_V_dout : STD_LOGIC_VECTOR (255 downto 0);
    signal result_V_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal result_V_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal result_V_empty_n : STD_LOGIC;

    component rsa_mod_exp IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        y : IN STD_LOGIC_VECTOR (255 downto 0);
        d : IN STD_LOGIC_VECTOR (255 downto 0);
        N : IN STD_LOGIC_VECTOR (255 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (255 downto 0) );
    end component;


    component rsa_Block_entry46_proc IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        p_read : IN STD_LOGIC_VECTOR (255 downto 0);
        x : OUT STD_LOGIC_VECTOR (255 downto 0);
        x_ap_vld : OUT STD_LOGIC );
    end component;


    component rsa_fifo_w256_d2_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (255 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (255 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (1 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (1 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component rsa_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        d : OUT STD_LOGIC_VECTOR (255 downto 0);
        N : OUT STD_LOGIC_VECTOR (255 downto 0);
        y : OUT STD_LOGIC_VECTOR (255 downto 0);
        x : IN STD_LOGIC_VECTOR (255 downto 0);
        x_ap_vld : IN STD_LOGIC;
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;



begin
    control_s_axi_U : component rsa_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        d => d,
        N => N,
        y => y,
        x => Block_entry46_proc_U0_x,
        x_ap_vld => Block_entry46_proc_U0_x_ap_vld,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    mod_exp_U0 : component rsa_mod_exp
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => mod_exp_U0_ap_start,
        ap_done => mod_exp_U0_ap_done,
        ap_continue => mod_exp_U0_ap_continue,
        ap_idle => mod_exp_U0_ap_idle,
        ap_ready => mod_exp_U0_ap_ready,
        y => y,
        d => d,
        N => N,
        ap_return => mod_exp_U0_ap_return);

    Block_entry46_proc_U0 : component rsa_Block_entry46_proc
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => Block_entry46_proc_U0_ap_start,
        ap_done => Block_entry46_proc_U0_ap_done,
        ap_continue => Block_entry46_proc_U0_ap_continue,
        ap_idle => Block_entry46_proc_U0_ap_idle,
        ap_ready => Block_entry46_proc_U0_ap_ready,
        p_read => result_V_dout,
        x => Block_entry46_proc_U0_x,
        x_ap_vld => Block_entry46_proc_U0_x_ap_vld);

    result_V_U : component rsa_fifo_w256_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => mod_exp_U0_ap_return,
        if_full_n => result_V_full_n,
        if_write => mod_exp_U0_ap_done,
        if_dout => result_V_dout,
        if_num_data_valid => result_V_num_data_valid,
        if_fifo_cap => result_V_fifo_cap,
        if_empty_n => result_V_empty_n,
        if_read => Block_entry46_proc_U0_ap_ready);




    Block_entry46_proc_U0_ap_continue <= ap_const_logic_1;
    Block_entry46_proc_U0_ap_start <= result_V_empty_n;
    ap_done <= Block_entry46_proc_U0_ap_done;
    ap_idle <= (mod_exp_U0_ap_idle and (result_V_empty_n xor ap_const_logic_1) and Block_entry46_proc_U0_ap_idle);
    ap_ready <= mod_exp_U0_ap_ready;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    mod_exp_U0_ap_continue <= result_V_full_n;
    mod_exp_U0_ap_start <= ap_start;
end behav;
