// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module rsa_Montgomery (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        N,
        a,
        b,
        ap_return
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [127:0] N;
input  [127:0] a;
input  [127:0] b;
output  [127:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    grp_Montgomery_Pipeline_Montgomery_fu_34_ap_start;
wire    grp_Montgomery_Pipeline_Montgomery_fu_34_ap_done;
wire    grp_Montgomery_Pipeline_Montgomery_fu_34_ap_idle;
wire    grp_Montgomery_Pipeline_Montgomery_fu_34_ap_ready;
wire   [129:0] grp_Montgomery_Pipeline_Montgomery_fu_34_m_V_7_0_out;
wire    grp_Montgomery_Pipeline_Montgomery_fu_34_m_V_7_0_out_ap_vld;
reg    grp_Montgomery_Pipeline_Montgomery_fu_34_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
wire   [129:0] zext_ln1031_fu_48_p1;
wire   [127:0] trunc_ln186_fu_57_p1;
wire   [0:0] icmp_ln1031_fu_51_p2;
wire   [127:0] sub_ln39_fu_61_p2;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 grp_Montgomery_Pipeline_Montgomery_fu_34_ap_start_reg = 1'b0;
end

rsa_Montgomery_Pipeline_Montgomery grp_Montgomery_Pipeline_Montgomery_fu_34(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Montgomery_Pipeline_Montgomery_fu_34_ap_start),
    .ap_done(grp_Montgomery_Pipeline_Montgomery_fu_34_ap_done),
    .ap_idle(grp_Montgomery_Pipeline_Montgomery_fu_34_ap_idle),
    .ap_ready(grp_Montgomery_Pipeline_Montgomery_fu_34_ap_ready),
    .a(a),
    .b(b),
    .N(N),
    .m_V_7_0_out(grp_Montgomery_Pipeline_Montgomery_fu_34_m_V_7_0_out),
    .m_V_7_0_out_ap_vld(grp_Montgomery_Pipeline_Montgomery_fu_34_m_V_7_0_out_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Montgomery_Pipeline_Montgomery_fu_34_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_Montgomery_Pipeline_Montgomery_fu_34_ap_start_reg <= 1'b1;
        end else if ((grp_Montgomery_Pipeline_Montgomery_fu_34_ap_ready == 1'b1)) begin
            grp_Montgomery_Pipeline_Montgomery_fu_34_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_Montgomery_Pipeline_Montgomery_fu_34_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_Montgomery_Pipeline_Montgomery_fu_34_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_return = ((icmp_ln1031_fu_51_p2[0:0] == 1'b1) ? trunc_ln186_fu_57_p1 : sub_ln39_fu_61_p2);

assign grp_Montgomery_Pipeline_Montgomery_fu_34_ap_start = grp_Montgomery_Pipeline_Montgomery_fu_34_ap_start_reg;

assign icmp_ln1031_fu_51_p2 = ((grp_Montgomery_Pipeline_Montgomery_fu_34_m_V_7_0_out < zext_ln1031_fu_48_p1) ? 1'b1 : 1'b0);

assign sub_ln39_fu_61_p2 = (trunc_ln186_fu_57_p1 - N);

assign trunc_ln186_fu_57_p1 = grp_Montgomery_Pipeline_Montgomery_fu_34_m_V_7_0_out[127:0];

assign zext_ln1031_fu_48_p1 = N;

endmodule //rsa_Montgomery
